services:
  host1:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: host1
    cap_add:
      - NET_ADMIN
    environment:
      DEFAULT_GW: 172.20.0.1
    networks:
      net10_1:
        ipv4_address: 172.20.0.2

  host2:
    build:
      context: .
      dockerfile: Dockerfile.host
    container_name: host2
    cap_add:
      - NET_ADMIN
    environment:
      DEFAULT_GW: 172.21.0.1
    networks:
      net10_2:
        ipv4_address: 172.21.0.2

  firewall:
    build:
      context: .
      dockerfile: Dockerfile.firewall
    container_name: firewall
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      LAN_IF: eth2
      LAN_GW: 172.22.1.2
      NET1_IF: eth0
      NET2_IF: eth1
    networks:
      net10_1:
        ipv4_address: 172.20.0.1
      net10_2:
        ipv4_address: 172.21.0.1
      lan:
        ipv4_address: 172.22.1.80
    volumes:
      - ./resources:/opt/basic_firewall/resources:ro

networks:
  net10_1:
    internal: true
    ipam:
      config:
        - subnet: 172.20.0.0/24
  net10_2:
    internal: true
    ipam:
      config:
        - subnet: 172.21.0.0/24
  lan:
    driver: macvlan
    driver_opts:
      parent: ${LAN_PARENT:-wlp131s0}
    ipam:
      config:
        - subnet: 172.22.1.0/24
          gateway: 172.22.1.2
